//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace wxhy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lycustomer
    {
        public int cstId { get; set; }
        public string name { get; set; }
        public Nullable<int> businessId { get; set; }
        public string openid { get; set; }
        public string nickname { get; set; }
        public Nullable<int> sex { get; set; }
        public string city { get; set; }
        public string country { get; set; }
        public string province { get; set; }
        public string language { get; set; }
        public string headimgurl { get; set; }
        public string subscribetime { get; set; }
        public string unionid { get; set; }
        public string remark { get; set; }
        public string groupid { get; set; }
        public string tagidlist { get; set; }
        public Nullable<int> csttype { get; set; }
        public string address { get; set; }
        public string store { get; set; }
        public string interestproduct { get; set; }
        public string referees { get; set; }
        public Nullable<int> integral { get; set; }
        public Nullable<int> storeId { get; set; }
        public string interestproductIdlist { get; set; }
        public string cell_phonenumber { get; set; }
    }
}
