//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace wxhy.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class wxhyEntities : DbContext
    {
        public wxhyEntities()
            : base("name=wxhyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<lybusiness> lybusiness { get; set; }
        public virtual DbSet<lyproduct> lyproduct { get; set; }
        public virtual DbSet<lystore> lystore { get; set; }
        public virtual DbSet<lycustomer> lycustomer { get; set; }
    }
}
